# Generated by Django 5.2.7 on 2025-10-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_type', models.CharField(choices=[('player', 'Player'), ('team', 'Team'), ('game', 'Game')], max_length=20)),
                ('favorite_id', models.IntegerField(help_text='ID of the favorited item (player, team, or game)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'favorite_type'], name='favorites_f_user_id_d93a95_idx')],
                'unique_together': {('user', 'favorite_type', 'favorite_id')},
            },
        ),
    ]
