# Generated by Django 5.2.7 on 2025-11-07 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('games', '0002_alter_game_options_alter_team_options_and_more'),
        ('players', '0002_alter_player_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='favorites_f_user_id_d93a95_idx',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'player'), ('user', 'team')},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('player', 'Player'), ('team', 'Team')], max_length=10),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.team'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='game',
        ),
    ]
