# Generated by Django 5.2.7 on 2025-10-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='Game ID from BallDontLie API', unique=True)),
                ('date', models.DateTimeField(help_text='Game date and time')),
                ('season', models.IntegerField(help_text='NBA season year')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final')], default='scheduled', max_length=20)),
                ('home_team_id', models.IntegerField()),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_team_score', models.IntegerField(blank=True, null=True)),
                ('visitor_team_id', models.IntegerField()),
                ('visitor_team_name', models.CharField(max_length=100)),
                ('visitor_team_score', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, help_text='Current period/quarter', null=True)),
                ('time', models.CharField(blank=True, help_text='Time remaining in period', max_length=20, null=True)),
                ('postseason', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='games_game_date_46ac91_idx'), models.Index(fields=['status'], name='games_game_status_da80c5_idx'), models.Index(fields=['season'], name='games_game_season_3d02ab_idx')],
            },
        ),
    ]
