# Generated by Django 5.2.7 on 2025-11-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_date_46ac91_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_status_da80c5_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visitor_team_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='upcoming', max_length=20),
        ),
    ]
