# Generated by Django 5.2.7 on 2025-11-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_last_na_1786cf_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='college',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated_at',
        ),
    ]
